#!/bin/sh

case "$1" in
  start)

    echo 49 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio49/direction
    echo 1 > /sys/class/gpio/gpio49/value
    test -f /etc/init.d/S10mdev && rm -f /etc/init.d/S10mdev
    rm -f /etc/init.d/S90* ; rm -f /etc/rc.pure/S90*
    /sbin/mdev -s
############ reset registers DSC2 ################
ls /proc/asound/card0 && /opt/mute.sh ; /usr/bin/aplay /opt/silent_quarter-second.wav ; touch /tmp/audiodone
##################################################
    
    cat /etc/random-seed >/dev/urandom
    /sbin/rndaddtoentcnt 1024
    echo 51 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio51/direction
    echo 1 > /sys/class/gpio/gpio51/value
    echo 60 > /sys/class/gpio/export
    echo in > /sys/class/gpio/gpio60/direction
    ls /dev/mmcblk0p2 && mount /dev/mmcblk0p1 /boot
    test -f /etc/output || echo USB > /etc/output
    echo "nameserver 1.1.1.1" >> /tmp/resolv.conf
    echo "nameserver 8.8.8.8" >> /tmp/resolv.conf
    grep -q "5.10.131" /proc/version && echo USB > /etc/output
    chmod 777 /run
    mkdir -p /tmp/db/dhcpcd
    chmod 777 /tmp/db/dhcpcd
    ;;
    
  stop)    
    /opt/mute.sh
        
    ;;    
 *)
    exit 1
esac










