#!/bin/sh


AUDIO=/tmp/audiodone
if [ -f "$AUDIO" ]; then
    echo "Audio card exist"
else
    n=1
    while [ $n -lt 50 ]
	do
	    n=$((n+1))
	    dev=`ls /proc/asound/card0`
    	    if [ -n "${dev}" ]; then
	    /opt/mute.sh ; /usr/bin/aplay /opt/silent_quarter-second.wav	
	    break
	    fi
        sleep 0.2
	done
fi


i=1
while [ $i -lt 300 ]
    do
	echo "Number: $i"
	i=$((i+1))
	network=`route |grep UG`
	if [[ -n "$network"  ]]; then
	break
	fi
    sleep 1
    done



