#!/bin/sh
#
# avahi-daemon init script

DAEMON=/usr/sbin/avahi-daemon
case "$1" in
    start)
	nice -n 19 $DAEMON -c || nice -n 19 $DAEMON -D
	;;
    stop)
	$DAEMON -c && $DAEMON -k
	;;
    reload)
	$DAEMON -c && $DAEMON -r
	;;
    *)
	echo "Usage: S50avahi-daemon {start|stop|reload}" >&2
	exit 1
	;;
esac
