#!/bin/sh

if grep -q USB /etc/output ; then
    for count in 1 2 3 4 5 6 7 8 9 10
    do
	usbdev=`aplay -l|grep USB`
       if [ -n "${usbdev}" ]; then
	break
       fi
       sleep 1
       if [ $count -eq 10 ]; then 
        echo "No USB audio device!"
        break
       fi
    done
fi    

