#!/bin/sh

case "$1" in
  start)
    echo none > /sys/class/leds/beaglebone\:green\:usr0/trigger
    echo none > /sys/class/leds/beaglebone\:green\:usr1/trigger
    echo none > /sys/class/leds/beaglebone\:green\:usr2/trigger
    echo none > /sys/class/leds/beaglebone\:green\:usr3/trigger
    # Turn OFF PMIC power LED
    i2cset -f -y 0 0x24 0x0b 0x6e
    i2cset -f -y 0 0x24 0x13 0x00
    i2cset -f -y 0 0x24 0x0b 0x6e
    i2cset -f -y 0 0x24 0x13 0x00
    # Turn ON PMIC power LED
    #i2cset -f -y 0 0x24 0x0b 0x6e
    #i2cset -f -y 0 0x24 0x13 0x38
    #i2cset -f -y 0 0x24 0x0b 0x6e
    #i2cset -f -y 0 0x24 0x13 0x38
    
    if [ -f /boot/am335x-boneblack.dtb ]; then
        mkdir /boot/dtbs
        mv -f /boot/*.dtb /boot/dtbs/
    fi

    /opt/unmute.sh

    echo /sbin/mdev > /proc/sys/kernel/hotplug
    /sbin/mdev -s
        
        ;;
  *)
	exit 1
esac
