#!/bin/bash

NAME=`hostname`_`ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`

/usr/bin/tcon \
--netif-for-deviceid eth0 \
-f $NAME \
--codec-mpegh false \
--codec-mqa false \
--model-name "OEM" \
--disable-app-security false \
--disable-web-security true \
--enable-mqa-passthrough true \
--log-level 0 \
--tc-certificate-path "/etc/ssl/private/tcon.crt" \
--clientid "VCjoaRrbaMU005Tk" \
#--playback-device "jack" \
> /dev/null 2>&1 &








