#!/bin/sh

case "$1" in
  start)
    touch /var/log/aprenderer.log
    ln -s -f /var/log/aprenderer.log /usr/aprenderer/aprenderer.log
    printf "Starting APlayer UPNP: "

    i=1
    while [ $i -lt 300 ]
    do
	echo "Number: $i"
	i=$((i+1))
	network=`route |grep UG`
	if [[ -n "$network"  ]]; then
	break
	fi
	sleep 1
    done

    MAC=`cat /sys/class/net/eth0/address`
    NAME=`hostname`_`ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`
    sed -i -e "s/<mac>.*<\/mac>/<mac>$MAC<\/mac>/g" /usr/aprenderer/upnp/config.xml
    sed -i -e "s/<name>.*<\/name>/<name>$NAME<\/name>/g" /usr/aprenderer/upnp/config.xml
    chown pure:pure /usr/aprenderer/*
    sudo -u pure /usr/aprenderer/upnp/squeeze2upnp -z -k -x /usr/aprenderer/upnp/config.xml > /dev/null 2>&1
    cd /usr/aprenderer; sudo -u pure ./ap2renderer > /dev/null 2>&1 && echo "OK" || echo "FAIL"
    sync    
    ;;
  stop)
	killall ap2renderer squeeze2upnp
    ;;
    *)	
	echo "Usage: $0 {start|stop}"
	exit 1
esac
