#!/bin/sh

# Sanity checks
test -f /etc/mpd.conf || exit 0

case "$1" in
  start)
        i=1
            while [ $i -lt 300 ]
                do
                echo "Number: $i"
                i=$((i+1))
                network=`route |grep UG`
                if [[ -n "$network"  ]]; then
                break
                fi
                sleep 1
            done

    printf "Starting mpd: "
    sync
    sudo -u pure /usr/bin/mpd 
    ;;
    stop)
    killall mpd
    ;;
    *)
	exit 1
esac