#!/bin/sh


case "$1" in
    start)
    printf "Starting RoonBrige: "
    MAC=`cat /sys/class/net/eth0/address | tr 'a-z' 'A-Z'`
    sed -i "s/^.*\"unique_id\".*/    \"unique_id\": \"$MAC\" ,/" /etc/raat.conf
    sudo -u pure /opt/RoonReady/raat_app /etc/raat.conf > /dev/null 2>&1 &
    
	;;
    stop)
    killall raat_app
    ;;
    *)
	exit 1
esac
