#! /bin/sh

# Additional options that are passed to Shairport Sync
OPTIONS="-d"

case "$1" in
    start)
	printf "Starting shairport-sync: "
	sudo -u pure /usr/bin/shairport-sync -d
	;;
    stop)
	printf "Stopping shairport-sync: "
	killall shairport-sync
	;;
    restart)
	$0 stop
	sleep 1
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
