#!/bin/sh

start() {
    printf "Starting Scream: "
    /usr/sbin/scream  > /dev/null 2>&1 &
    renice -15 `pidof scream`
    }
stop() {
    killall -9 scream
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
