#!/bin/sh

start() {
	printf "Starting shairport-sync: "
	/usr/bin/shairport-sync -d
	renice -15 `pidof shairport-sync`
    }
stop() {
    killall -9 shairport-sync
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
